from nutrition_tracker.repository.food_nutrition_repository import output_format_with_units, food_data
from nutrition_tracker.enums.serving_enum import Serving_Enum as serving
import re
from nutrition_tracker.service.nutrition_tracker_service import NutritionalValue



